# Generated by Django 3.2.4 on 2021-06-14 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Pass', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('RollNo', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=30)),
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
                ('ContactNo', models.CharField(max_length=13)),
                ('Placed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SName', models.CharField(max_length=200)),
                ('RollNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PName', models.CharField(max_length=200)),
                ('PLink', models.URLField(max_length=300)),
                ('RollNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem1', models.IntegerField()),
                ('sem2', models.IntegerField()),
                ('sem3', models.IntegerField()),
                ('sem4', models.IntegerField()),
                ('sem5', models.IntegerField()),
                ('sem6', models.IntegerField()),
                ('sem7', models.IntegerField()),
                ('sem8', models.IntegerField()),
                ('RollNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('COrg', models.CharField(max_length=200)),
                ('CName', models.CharField(max_length=200)),
                ('CID', models.CharField(max_length=200)),
                ('CLink', models.URLField(max_length=300)),
                ('RollNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
    ]
