# Generated by Django 3.2.4 on 2021-06-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('CName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('NoStudent', models.IntegerField()),
                ('AvgPack', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CName', models.CharField(max_length=200)),
                ('JTitle', models.CharField(max_length=200)),
                ('Avg', models.IntegerField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
